replicaCount: 2

## Set default image, imageTag, and imagePullPolicy.
## ref: https://hub.docker.com/r/apache/nifi/
##
image:
  repository: nathluu/nifi
  tag: "1.23.2-r8"
  pullPolicy: "IfNotPresent"

properties:
  isNode: true
  webProxyHost: nifi-release.aks-npe.trustbase.vn,nifi-release.nifi-demo.svc:8443,nifi-release.nifi-demo.svc.cluster.local:8443

auth:
  admin:
  oidc:
    enabled: true
    discoveryUrl: https://login.microsoftonline.com/<tenantid>/v2.0/.well-known/openid-configuration
    clientId: 
    clientSecret: 
    claimIdentifyingUser: email
    admin: 
    additionalScopes: profile

persistence:
  enabled: true

zookeeper:
  ## If true, install the Zookeeper chart
  ## ref: https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/values.yaml
  enabled: true
  ## If the Zookeeper Chart is disabled a URL and port are required to connect
  url: ""
  port: 2181
  replicaCount: 1

certManager:
  enabled: true
  keystorePasswd: 12345678x@X
  truststorePasswd: 12345678x@X