replicaCount: 1

## Set default image, imageTag, and imagePullPolicy.
## ref: https://hub.docker.com/r/apache/nifi/
##
image:
  repository: nathluu/nifi
  tag: "1.23.2-r8"
  pullPolicy: "IfNotPresent"

properties:
  isNode: true